# Generated by Django 5.2.7 on 2025-10-17 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MataKuliah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_mk', models.CharField(max_length=10, unique=True)),
                ('nama_mk', models.CharField(max_length=100)),
                ('sks', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('deskripsi', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramStudi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_prodi', models.CharField(max_length=10, unique=True)),
                ('nama_prodi', models.CharField(max_length=100)),
                ('jenjang', models.CharField(choices=[('D3', 'Diploma 3'), ('S1', 'Sarjana'), ('S2', 'Magister'), ('S3', 'Doktor')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Dosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nidn', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('jabatan', models.CharField(max_length=50)),
                ('no_telp', models.CharField(blank=True, max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('program_studi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.programstudi')),
            ],
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_kelas', models.CharField(max_length=20, unique=True)),
                ('tahun_ajaran', models.CharField(max_length=9)),
                ('semester', models.CharField(choices=[('Ganjil', 'Ganjil'), ('Genap', 'Genap')], max_length=10)),
                ('kuota', models.IntegerField()),
                ('dosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.dosen')),
                ('mata_kuliah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.matakuliah')),
            ],
        ),
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari', models.CharField(choices=[('Senin', 'Senin'), ('Selasa', 'Selasa'), ('Rabu', 'Rabu'), ('Kamis', 'Kamis'), ('Jumat', 'Jumat'), ('Sabtu', 'Sabtu')], max_length=10)),
                ('jam_mulai', models.TimeField()),
                ('jam_selesai', models.TimeField()),
                ('ruangan', models.CharField(max_length=20)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal', to='academic.kelas')),
            ],
            options={
                'ordering': ['hari', 'jam_mulai'],
            },
        ),
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(max_length=15, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('angkatan', models.IntegerField()),
                ('no_telp', models.CharField(blank=True, max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('program_studi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.programstudi')),
            ],
        ),
        migrations.CreateModel(
            name='KRS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_daftar', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak')], default='pending', max_length=10)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.kelas')),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.mahasiswa')),
            ],
            options={
                'unique_together': {('mahasiswa', 'kelas')},
            },
        ),
        migrations.CreateModel(
            name='Nilai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai_huruf', models.CharField(blank=True, choices=[('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=2, null=True)),
                ('nilai_angka', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('krs', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='academic.krs')),
            ],
        ),
        migrations.AddField(
            model_name='matakuliah',
            name='program_studi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.programstudi'),
        ),
        migrations.CreateModel(
            name='Presensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('pertemuan_ke', models.IntegerField()),
                ('status', models.CharField(choices=[('hadir', 'Hadir'), ('izin', 'Izin'), ('sakit', 'Sakit'), ('alpha', 'Alpha')], max_length=10)),
                ('keterangan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('krs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presensi', to='academic.krs')),
            ],
            options={
                'ordering': ['tanggal'],
                'unique_together': {('krs', 'pertemuan_ke')},
            },
        ),
    ]
