# Generated by Django 5.2.7 on 2025-10-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosen',
            name='alamat',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dosen',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='dosen',
            name='foto',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='dosen',
            name='gelar_belakang',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='dosen',
            name='gelar_depan',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='dosen',
            name='jenis_kelamin',
            field=models.CharField(blank=True, choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=10),
        ),
        migrations.AddField(
            model_name='dosen',
            name='nip',
            field=models.CharField(blank=True, max_length=30, verbose_name='NIP'),
        ),
        migrations.AddField(
            model_name='dosen',
            name='pendidikan_terakhir',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='dosen',
            name='status_kepegawaian',
            field=models.CharField(blank=True, choices=[('PNS', 'Pegawai Negeri Sipil'), ('Kontrak', 'Dosen Kontrak'), ('Tetap', 'Dosen Tetap Yayasan'), ('Honorer', 'Dosen Honorer')], max_length=50),
        ),
        migrations.AddField(
            model_name='dosen',
            name='tanggal_lahir',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dosen',
            name='tempat_lahir',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='agama',
            field=models.CharField(blank=True, choices=[('Islam', 'Islam'), ('Kristen', 'Kristen'), ('Katolik', 'Katolik'), ('Hindu', 'Hindu'), ('Buddha', 'Buddha'), ('Konghucu', 'Konghucu')], max_length=20),
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='alamat',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='alamat_ortu',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='foto',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='jenis_kelamin',
            field=models.CharField(blank=True, choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=10),
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='nama_ayah',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='nama_ibu',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='no_telp_ortu',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='pekerjaan_ayah',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='pekerjaan_ibu',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='semester_berjalan',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='status_mahasiswa',
            field=models.CharField(choices=[('Aktif', 'Aktif'), ('Cuti', 'Cuti'), ('Lulus', 'Lulus'), ('DO', 'Drop Out'), ('Mengundurkan Diri', 'Mengundurkan Diri')], default='Aktif', max_length=20),
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='tanggal_lahir',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='tempat_lahir',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
