# Generated by Django 5.2.7 on 2025-10-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosen',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='dosen/'),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='mahasiswa/'),
        ),
    ]
