# Generated by Django 5.2.7 on 2025-10-22 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_alter_dosen_foto_alter_mahasiswa_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fakultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_fakultas', models.CharField(max_length=10, unique=True)),
                ('nama_fakultas', models.CharField(max_length=100)),
                ('dekan', models.CharField(blank=True, max_length=100)),
                ('no_telp', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('alamat', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ruang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_ruang', models.CharField(max_length=10, unique=True)),
                ('nama_ruang', models.CharField(max_length=50)),
                ('gedung', models.CharField(blank=True, max_length=20)),
                ('lantai', models.CharField(blank=True, max_length=10)),
                ('kapasitas', models.IntegerField(default=0)),
                ('jenis_ruang', models.CharField(choices=[('Kelas', 'Kelas'), ('Lab', 'Laboratorium'), ('Seminar', 'Ruang Seminar'), ('Auditorium', 'Auditorium'), ('Kantor', 'Ruang Kantor')], default='Kelas', max_length=20)),
                ('fasilitas', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Aktif', 'Aktif'), ('Maintenance', 'Maintenance'), ('Tidak Aktif', 'Tidak Aktif')], default='Aktif', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='programstudi',
            name='kaprodi',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='programstudi',
            name='fakultas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.fakultas'),
        ),
    ]
