# Generated by Django 5.2.7 on 2025-10-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_fakultas_ruang_programstudi_kaprodi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_semester', models.CharField(max_length=50)),
                ('kode_semester', models.CharField(max_length=10, unique=True)),
                ('tahun_ajaran', models.CharField(max_length=9)),
                ('jenis_semester', models.CharField(choices=[('Ganjil', 'Ganjil'), ('Genap', 'Genap'), ('Pendek', 'Pendek')], max_length=10)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('aktif', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-tahun_ajaran', '-jenis_semester'],
            },
        ),
    ]
