# Generated by Django 5.2.7 on 2025-10-22 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_semester'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dosen',
            options={'verbose_name': 'Dosen', 'verbose_name_plural': 'Dosen'},
        ),
        migrations.AlterModelOptions(
            name='fakultas',
            options={'verbose_name': 'Fakultas', 'verbose_name_plural': 'Fakultas'},
        ),
        migrations.AlterModelOptions(
            name='kelas',
            options={'verbose_name': 'Kelas', 'verbose_name_plural': 'Kelas'},
        ),
        migrations.AlterModelOptions(
            name='mahasiswa',
            options={'verbose_name': 'Mahasiswa', 'verbose_name_plural': 'Mahasiswa'},
        ),
        migrations.AlterModelOptions(
            name='matakuliah',
            options={'verbose_name': 'Mata Kuliah', 'verbose_name_plural': 'Mata Kuliah'},
        ),
        migrations.AlterModelOptions(
            name='programstudi',
            options={'verbose_name': 'Program Studi', 'verbose_name_plural': 'Program Studi'},
        ),
        migrations.AlterModelOptions(
            name='ruang',
            options={'verbose_name': 'Ruang', 'verbose_name_plural': 'Ruang'},
        ),
    ]
