# Generated by Django 5.2.7 on 2025-10-22 17:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_alter_dosen_options_alter_fakultas_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fakultas',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fakultas',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
